services:
  squid:
    image: ubuntu/squid
    ports:
      - "3128:3128"

    volumes:
      - ${PWD}/squid.conf:/etc/squid/conf.d/squid.conf
      - ${PWD}/passwords:/etc/squid/passwords

    restart: always
